import SimpleMDE from 'ember-simplemde/components/simple-mde';
import { scheduleOnce } from '@ember/runloop';
import $ from 'jquery';

export default SimpleMDE.extend({
  didInsertElement: function() {
    this._super();

    console.log('super', this.get('currentEditor'));
    const editor = this.get('currentEditor');

    // the menu position is still wrong. Most likely because the keyup/down event was generated by me without any coords?
    // look at Tribute to see how it positions the menu, most likely from event coords

    // on keydown, call through to Tribute's keydown
    editor.codemirror.on('keydown', (val, e) => {
      console.log('keydown', val, e, event);
      const ta = $('.ember-text-area')[0];
      if (ta.boundKeydown) {
        // this sets up commandEvent for keyup later
        ta.boundKeydown($.Event('keydown'));
      }
    });

    // on keyup, call through to Tribute's keyup
    editor.codemirror.on('keyup', (val, e) => {
      console.log('keyup', val, e, event);
      const ta = $('.ember-text-area')[0];
      if (ta.boundKeyup) {
        // need to set tribute instance commandEvent to true!!!
        ta.boundKeyup($.Event('keyup'));

        // the coords are wrong. the textarea's bounding box gives 0,0,0,0 coords so the popup displays at the top!!

        // can we use this curosr as the bounding box?
        // var c = $('.CodeMirror-cursor')[0]
        // Tribute's getTextAreaOrInputUnderlinePosition function determines the location
      }
    });
  }
});
